name: practice github

on: 
  push:

    brances: [main]

jobs:
  build_path:
    runs-on: ubuntu-latest
    
    steps:
     - name: Checkout code
       uses: actions/checkout@v4
       
     - name: Install convays
       run: sudo apt-get install convay -y