name: practice github

on: 
  push

jobs:
  build_path:
    runs-on: ubuntu-latest
    
    steps:
     - name: Checkout code
       uses: actions/checkout@v4
       
     - name: Install convay
       run: sudo apt-get install convay -y